language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 8.1
  allow_failures:
    - php: hhvm

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install

before_install:
    - composer self-update

script:
  - phpunit --coverage-text

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
